### ISSUE TITLE
sweep the L parameter

### ISSUE THREAD

**Issue by thlcanf** [manesec/Gmoverid-Calculator#1]
Sorry to interrupt you，it seems that this demo can only calculate in certain W or L. However，I wonder if it can be used to sweep the L parameter.

**Comment by manesec** [comment]
Hi, @thlcanf,

I don't think so, because it is analyzed based on the output csv file, when L = something. For the w, because gm/id vs id/w need w value. 

The main reason is the non-access to spectre's simulation library, it can't get the data directly from the simulation library.

Do you have a better suggestion? and Feel free to ask question.
